# encoding: UTF-8

require 'spec_helper'

require VANE_LIB_DIR + '/vane_helper'

SPEC_FIXTURES_VANE_DIR                = SPEC_FIXTURES_DIR + '/vane'
SPEC_FIXTURES_VANE_WEB_SITE_DIR       = SPEC_FIXTURES_VANE_DIR + '/web_site'
SPEC_FIXTURES_VANE_WP_TARGET_DIR      = SPEC_FIXTURES_VANE_DIR + '/wp_target'
SPEC_FIXTURES_VANE_VANE_OPTIONS_DIR = SPEC_FIXTURES_VANE_DIR + '/vane_options'
SPEC_FIXTURES_VANE_WP_THEME_DIR       = SPEC_FIXTURES_VANE_DIR + '/wp_theme'
SPEC_FIXTURES_VANE_WP_PLUGIN_DIR      = SPEC_FIXTURES_VANE_DIR + '/wp_plugin'
SPEC_FIXTURES_VANE_WP_VERSION_DIR     = SPEC_FIXTURES_VANE_DIR + '/wp_version'
